# Generated by Django 5.2.5 on 2025-08-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=20)),
                ('sinopsis', models.TextField()),
                ('portada', models.ImageField(blank=True, null=True, upload_to='recursos/portadas')),
                ('fecha_publicacion', models.DateField()),
            ],
        ),
    ]
