# Generated by Django 5.2.5 on 2025-08-20 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0006_alter_libro_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='recursos/portadas/'),
        ),
    ]
